version: "3"

services:
  #######################################
  # API
  #######################################
  api:
    build:
      context: ./todomvc-api/
      args:
        ARTIFACT_VERSION: ${ARTIFACT_VERSION:-0.0.1-SNAPSHOT}
    image: ncarlier/keycloak-todomvc-api
    env_file: ./todomvc-api/conf.env
    volumes:
      - conf-data:/etc/todomvc:ro
    extra_hosts:
      devbox: 172.17.0.1
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=PathPrefix:/api"

  #######################################
  # Webapp
  #######################################
  app:
    build:
      context: ./todomvc-app/
    image: ncarlier/keycloak-todomvc-app
    volumes:
      - conf-data:/usr/share/nginx/html/conf:ro
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/app"

  #######################################
  # CLI
  #######################################
  cli:
    build:
      context: ./todomvc-cli/
    image: ncarlier/keycloak-todomvc-cli
    env_file: ./todomvc-cli/conf.env
    labels:
      - "traefik.enable=false"

  #######################################
  # Slides
  #######################################
  slides:
    build:
      context: ./slides/
    image: ncarlier/keycloak-todomvc-slides
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/slides"

