version: "3"

services:
  #######################################
  # API
  #######################################
  api:
    build:
      context: ./todomvc-api/
      args:
        ARTIFACT_VERSION: ${ARTIFACT_VERSION:-0.0.1-SNAPSHOT}
    image: ncarlier/keycloak-todomvc-api
    env_file: ./todomvc-api/conf.env
    volumes:
      - conf-data:/etc/todomvc:ro
    extra_hosts:
      devbox: 172.17.0.1
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=PathPrefix:/api"

  #######################################
  # Webapp
  #######################################
  app:
    build:
      context: ./todomvc-app/
    image: ncarlier/keycloak-todomvc-app
    volumes:
      - conf-data:/usr/share/nginx/html/conf:ro
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/app"
  cli:
    build:
      context: ./todomvc-cli/
      args:
        TODOMVC_CLIENT_SECRET: 663c5cb1-20cb-48a4-b3c1-1fcc2044e4b7
        API_ENDPOINT: http://devbox/api/
        AUTH_ENDPOINT: http://devbox/auth/
    image: ncarlier/keycloak-todomvc-cli
